/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "asd.check" instead.
 */

#include <check.h>
#include <limits.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

#include "s21_math.h"

START_TEST(pow_test) {
  long double x1 = s21_pow((double)_i * 5.12, 2.21);
  long double x2 = pow((double)_i * 5.12, 2.21);
  ck_assert_ldouble_eq_tol(x1, x2, 1e-06);
}
END_TEST
START_TEST(pow_test2) {
  char str1[1000], str2[1000];
  str1[0] =
      snprintf(str1, sizeof(str1), "%.6Lf", s21_pow((double)_i * 5.12, _i));
  str2[0] = snprintf(str2, sizeof(str2), "%.6f", pow((double)_i * 5.12, _i));
  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(p10) { printf("10%%\n"); }
END_TEST
// -----------------------
START_TEST(sin_test) {
  long double x1 = s21_sin((double)_i * 5.12);
  long double x2 = sin((double)_i * 5.12);
  ck_assert_ldouble_eq_tol(x1, x2, EPS_6);
}
END_TEST
START_TEST(sin_test1) {
  long double x1 = s21_sin((double)_i / 10);
  long double x2 = sin((double)_i / 10);
  ck_assert_ldouble_eq_tol(x1, x2, EPS_6);
}
END_TEST
START_TEST(sin_test2) {
  long double x1 = s21_sin((double)_i * 5.12);
  long double x2 = sin((double)_i * 5.12);
  ck_assert_ldouble_eq_tol(x1, x2, EPS_6);
}
END_TEST
START_TEST(sin_test3) {
  for (int i = 0; i < _i; i++) {
    int x = rand_r((unsigned *)&x);
    long double x1 = s21_sin(x / S21_M_PI);
    long double x2 = sin(x / S21_M_PI);
    ck_assert_ldouble_eq_tol(x1, x2, EPS_6);
  }
}
END_TEST
START_TEST(p20) { printf("20%%\n"); }
END_TEST
// -----------------------
START_TEST(cos_test) {
  long double x1 = s21_cos((double)_i * 5.12);
  long double x2 = cos((double)_i * 5.12);
  ck_assert_ldouble_eq_tol(x1, x2, EPS_6);
}
END_TEST
START_TEST(cos_test1) {
  long double x1 = s21_cos((double)_i / 10);
  long double x2 = cos((double)_i / 10);
  ck_assert_ldouble_eq_tol(x1, x2, EPS_6);
}
END_TEST
START_TEST(cos_test2) {
  long double x1 = s21_cos((double)_i * 5.12);
  long double x2 = cos((double)_i * 5.12);
  ck_assert_ldouble_eq_tol(x1, x2, EPS_6);
}
END_TEST
START_TEST(cos_test3) {
  for (int i = 0; i < _i; i++) {
    int x = rand_r((unsigned *)&x);
    long double x1 = s21_cos(x / S21_M_PI);
    long double x2 = cos(x / S21_M_PI);
    ck_assert_ldouble_eq_tol(x1, x2, EPS_6);
  }
}
END_TEST
// -----------------------
START_TEST(sqrt_test) {
  char str1[1000], str2[1000];
  str1[999] =
      snprintf(str1, sizeof(str1), "%.6Lf", s21_sqrt((double)_i * 5.12));
  str2[999] = snprintf(str2, sizeof(str2), "%.6f", sqrt((double)_i * 5.12));
  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(sqrt_test2) {
  char str1[1000], str2[1000];
  str1[999] =
      snprintf(str1, sizeof(str1), "%.6Lf", s21_sqrt((double)_i * 5.12));
  str2[999] = snprintf(str2, sizeof(str2), "%.6f", sqrt((double)_i * 5.12));
  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(p30) { printf("30%%\n"); }
END_TEST
// -----------------------
START_TEST(tan_test) {
  char str1[1000], str2[1000];
  str1[999] = snprintf(str1, sizeof(str1), "%.6Lf", s21_tan((double)_i * 5.12));
  str2[999] = snprintf(str2, sizeof(str2), "%.6f", tan((double)_i * 5.12));
  ck_assert_str_eq(str1, str2);
}
END_TEST
// -----------------------
START_TEST(abs_test) {
  int x1 = s21_abs(_i * 42);
  int x2 = abs(_i * 42);
  ck_assert_int_eq(x1, x2);
}
END_TEST
START_TEST(abs_test1) {
  for (int i = 0; i < _i; i++) {
    int x = rand_r((unsigned *)&x);
    int x1 = s21_abs(_i - x);
    int x2 = abs(_i - x);
    ck_assert_int_eq(x1, x2);
  }
}
END_TEST
START_TEST(abs_test2) {
  for (int i = 0; i < _i; i++) {
    int x = rand_r((unsigned *)&x);
    int x1 = s21_abs(x);
    int x2 = abs(x);
    ck_assert_int_eq(x1, x2);
  }
}
END_TEST
START_TEST(p40) { printf("40%%\n"); }
END_TEST
// -----------------------
START_TEST(acos_test) {
  char str1[1000], str2[1000];
  str1[0] = snprintf(str1, sizeof(str1), "%.6Lf", s21_acos((double)_i * 5.12));
  str2[0] = snprintf(str2, sizeof(str2), "%.6f", acos((double)_i * 5.12));
  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(acos_test1) {
  char str1[1000], str2[1000];
  str1[999] = snprintf(str1, sizeof(str1), "%.6Lf", s21_acos((double)_i / 10));
  str2[999] = snprintf(str2, sizeof(str2), "%.6f", acos((double)_i / 10));
  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(acos_test2) {
  for (int i = 0; i < _i; i++) {
    char str1[1000], str2[1000];
    int x = rand_r((unsigned *)&x);
    str1[0] = snprintf(str1, sizeof(str1), "%.6Lf", s21_acos((double)_i - x));
    str2[0] = snprintf(str2, sizeof(str2), "%.6f", acos((double)_i - x));
    ck_assert_str_eq(str1, str2);
  }
}
END_TEST
// -----------------------
START_TEST(asin_test) {
  char str1[1000], str2[1000];
  str1[0] = snprintf(str1, sizeof(str1), "%.6Lf", s21_asin((double)_i * 5.12));
  str2[0] = snprintf(str2, sizeof(str2), "%.6f", asin((double)_i * 5.12));
  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(asin_test1) {
  char str1[1000], str2[1000];
  str1[999] = snprintf(str1, sizeof(str1), "%.6Lf", s21_asin((double)_i / 10));
  str2[999] = snprintf(str2, sizeof(str2), "%.6f", asin((double)_i / 10));
  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(asin_test2) {
  for (int i = 0; i < _i; i++) {
    char str1[1000], str2[1000];
    int x = rand_r((unsigned *)&x);
    str1[0] = snprintf(str1, sizeof(str1), "%.6Lf", s21_asin((double)_i - x));
    str2[0] = snprintf(str2, sizeof(str2), "%.6f", asin((double)_i - x));
    ck_assert_str_eq(str1, str2);
  }
}
END_TEST
START_TEST(p50) { printf("50%%\n"); }
END_TEST
// -----------------------
START_TEST(atan_test1) {
  char str1[1000], str2[1000];
  str1[999] = snprintf(str1, sizeof(str1), "%.6Lf", s21_atan((double)_i / 10));
  str2[999] = snprintf(str2, sizeof(str2), "%.6f", atan((double)_i / 10));
  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(p60) { printf("60%%\n"); }
END_TEST
// -----------------------
START_TEST(fabs_test) {
  char str1[1000], str2[1000];
  str1[0] = snprintf(str1, sizeof(str1), "%.6Lf", s21_fabs((double)_i * 5.12));
  str2[0] = snprintf(str2, sizeof(str2), "%.6f", fabs((double)_i * 5.12));
  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(fabs_test1) {
  char str1[1000], str2[1000];
  str1[999] = snprintf(str1, sizeof(str1), "%.6Lf", s21_fabs((double)_i / 10));
  str2[999] = snprintf(str2, sizeof(str2), "%.6f", fabs((double)_i / 10));
  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(fabs_test2) {
  for (int i = 0; i < _i; i++) {
    char str1[1000], str2[1000];
    int x = rand_r((unsigned *)&x);
    str1[0] = snprintf(str1, sizeof(str1), "%.6Lf", s21_fabs((double)_i - x));
    str2[0] = snprintf(str2, sizeof(str2), "%.6f", fabs((double)_i - x));
    ck_assert_str_eq(str1, str2);
  }
}
START_TEST(p70) { printf("70%%\n"); }
END_TEST
// -----------------------
START_TEST(floor_test) {
  char str1[1000], str2[1000];
  str1[0] = snprintf(str1, sizeof(str1), "%.6Lf", s21_floor((double)_i * 5.12));
  str2[0] = snprintf(str2, sizeof(str2), "%.6f", floor((double)_i * 5.12));
  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(floor_test1) {
  char str1[1000], str2[1000];
  str1[999] = snprintf(str1, sizeof(str1), "%.6Lf", s21_floor((double)_i / 10));
  str2[999] = snprintf(str2, sizeof(str2), "%.6f", floor((double)_i / 10));
  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(floor_test2) {
  for (int i = 0; i < _i; i++) {
    char str1[1000], str2[1000];
    int x = rand_r((unsigned *)&x);
    str1[0] = snprintf(str1, sizeof(str1), "%.6Lf", s21_floor((double)_i - x));
    str2[0] = snprintf(str2, sizeof(str2), "%.6f", floor((double)_i - x));
    ck_assert_str_eq(str1, str2);
  }
}
// -----------------------
START_TEST(fmod_test) {
  char str1[1000], str2[1000];
  str1[0] = snprintf(str1, sizeof(str1), "%.6Lf",
                     s21_fmod((double)_i * 5.12, S21_M_PI / _i * 0.12416541));
  str2[0] = snprintf(str2, sizeof(str2), "%.6f",
                     fmod((double)_i * 5.12, S21_M_PI / _i * 0.12416541));
  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(fmod_test1) {
  char str1[1000], str2[1000];
  str1[999] = snprintf(str1, sizeof(str1), "%.6Lf",
                       s21_fmod((double)_i / 10, S21_M_PI * 2.14616712));
  str2[999] = snprintf(str2, sizeof(str2), "%.6f",
                       fmod((double)_i / 10, S21_M_PI * 2.14616712));
  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(fmod_test2) {
  for (int i = 0; i < _i; i++) {
    char str1[1000], str2[1000];
    str1[999] = snprintf(str1, sizeof(str1), "%.6f",
                         fmod((double)_i + S21_M_PI, _i * 0.12472524));
    str2[999] = snprintf(str2, sizeof(str2), "%.6Lf",
                         s21_fmod((double)_i + S21_M_PI, _i * 0.12472524));
    ck_assert_str_eq(str1, str2);
  }
}
START_TEST(p80) { printf("80%%\n"); }
END_TEST
// -----------------------
START_TEST(log_test) {
  char str1[1000], str2[1000];
  str1[999] = snprintf(str1, sizeof(str1), "%.6Lf", s21_log((double)_i * 5.12));
  str2[999] = snprintf(str2, sizeof(str2), "%.6f", log((double)_i * 5.12));
  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(log_test1) {
  char str1[1000], str2[1000];
  str1[999] = snprintf(str1, sizeof(str1), "%.6Lf", s21_floor((double)_i / 10));
  str2[999] = snprintf(str2, sizeof(str2), "%.6f", floor((double)_i / 10));
  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(log_test2) {
  for (int i = 0; i < _i; i++) {
    char str1[1000], str2[1000];
    int x = rand_r((unsigned *)&x);
    str1[0] = snprintf(str1, sizeof(str1), "%.6Lf", s21_log((double)_i - x));
    str2[0] = snprintf(str2, sizeof(str2), "%.6f", log((double)_i - x));
    ck_assert_str_eq(str1, str2);
  }
}
// -----------------------
START_TEST(ceil_test) {
  char str1[1000], str2[1000];
  str1[999] =
      snprintf(str1, sizeof(str1), "%.6Lf", s21_ceil((double)_i * 5.12));
  str2[999] = snprintf(str2, sizeof(str2), "%.6f", ceil((double)_i * 5.12));
  ck_assert_str_eq(str1, str2);
}
START_TEST(ceil_test1) {
  char str1[1000], str2[1000];
  str1[999] = snprintf(str1, sizeof(str1), "%.6Lf", s21_ceil((double)_i / 10));
  str2[999] = snprintf(str2, sizeof(str2), "%.6f", ceil((double)_i / 10));
  ck_assert_str_eq(str1, str2);
}
END_TEST
START_TEST(ceil_test2) {
  for (int i = 0; i < _i; i++) {
    char str1[1000], str2[1000];
    int x = rand_r((unsigned *)&x);
    str1[0] = snprintf(str1, sizeof(str1), "%.6Lf", s21_ceil((double)_i - x));
    str2[0] = snprintf(str2, sizeof(str2), "%.6f", ceil((double)_i - x));
    ck_assert_str_eq(str1, str2);
  }
}
END_TEST
START_TEST(p90) { printf("90%%\n"); }
END_TEST
// -----------------------
START_TEST(exp_test) {
  char str1[1000], str2[1000];
  str1[999] = snprintf(str1, sizeof(str1), "%.6Lf", s21_exp((double)_i / 1000));
  str2[999] = snprintf(str2, sizeof(str2), "%.6f", exp((double)_i / 1000));
  ck_assert_str_eq(str1, str2);
}
START_TEST(exp_test2) {
  for (int i = 0; i < _i; i++) {
    char str1[1000], str2[1000];
    int x = rand_r((unsigned *)&x);
    str1[999] = snprintf(str1, sizeof(str1), "%.6Lf", s21_exp((double)_i - x));
    str2[999] = snprintf(str2, sizeof(str2), "%.6f", exp((double)_i - x));
    ck_assert_str_eq(str1, str2);
  }
}
END_TEST
// -----------------------
int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_loop_test(tc1_1, pow_test, S21_M_PI, S21_M_PI + 1000);
  tcase_add_loop_test(tc1_1, pow_test2, -1000, 0);
  // 10
  tcase_add_test(tc1_1, p10);
  //
  tcase_add_loop_test(tc1_1, sin_test, S21_M_PI, S21_M_PI + 1000);
  tcase_add_loop_test(tc1_1, sin_test1, -500, 500);
  tcase_add_loop_test(tc1_1, sin_test2, -1000, 0);
  tcase_add_loop_test(tc1_1, sin_test3, 0, 1000);
  // 20
  tcase_add_test(tc1_1, p20);
  //
  tcase_add_loop_test(tc1_1, cos_test, S21_M_PI, S21_M_PI + 1000);
  tcase_add_loop_test(tc1_1, cos_test1, -500, 500);
  tcase_add_loop_test(tc1_1, cos_test2, -1000, 0);
  tcase_add_loop_test(tc1_1, cos_test3, 0, 1000);

  tcase_add_loop_test(tc1_1, sqrt_test, S21_M_PI, S21_M_PI + 1000);
  tcase_add_loop_test(tc1_1, sqrt_test2, -1000, 0);
  // 30
  tcase_add_test(tc1_1, p30);
  //
  tcase_add_loop_test(tc1_1, tan_test, S21_M_PI, S21_M_PI + 100);

  tcase_add_loop_test(tc1_1, abs_test, S21_M_PI, S21_M_PI + 1000);
  tcase_add_loop_test(tc1_1, abs_test1, 0, 1000);
  tcase_add_loop_test(tc1_1, abs_test2, 0, 1000);
  // 40
  tcase_add_test(tc1_1, p40);
  //
  tcase_add_loop_test(tc1_1, acos_test, S21_M_PI, S21_M_PI + 1000);
  tcase_add_loop_test(tc1_1, acos_test1, -500, 500);
  tcase_add_loop_test(tc1_1, acos_test2, 0, 1000);

  tcase_add_loop_test(tc1_1, asin_test, S21_M_PI, S21_M_PI + 1000);
  tcase_add_loop_test(tc1_1, asin_test1, -500, 500);
  tcase_add_loop_test(tc1_1, asin_test2, 0, 1000);
  // 50
  tcase_add_test(tc1_1, p50);
  //
  tcase_add_loop_test(tc1_1, atan_test1, 0, 1000);
  // 60
  tcase_add_test(tc1_1, p60);
  //
  tcase_add_loop_test(tc1_1, fabs_test, S21_M_PI, S21_M_PI + 1000);
  tcase_add_loop_test(tc1_1, fabs_test1, 0, 1000);
  tcase_add_loop_test(tc1_1, fabs_test2, 0, 1000);
  // 70
  tcase_add_test(tc1_1, p70);
  //
  tcase_add_loop_test(tc1_1, floor_test, S21_M_PI, S21_M_PI + 1000);
  tcase_add_loop_test(tc1_1, floor_test1, 0, 1000);
  tcase_add_loop_test(tc1_1, floor_test2, 0, 1000);

  tcase_add_loop_test(tc1_1, fmod_test, S21_M_PI, S21_M_PI + 1000);
  tcase_add_loop_test(tc1_1, fmod_test1, 0, 1000);
  tcase_add_loop_test(tc1_1, fmod_test2, 0, 1000);
  // 80
  tcase_add_test(tc1_1, p80);
  //
  tcase_add_loop_test(tc1_1, log_test, S21_M_PI, S21_M_PI + 1000);
  tcase_add_loop_test(tc1_1, log_test1, 0, 1000);
  tcase_add_loop_test(tc1_1, log_test2, 0, 1000);

  tcase_add_loop_test(tc1_1, ceil_test, S21_M_PI, S21_M_PI + 1000);
  tcase_add_loop_test(tc1_1, ceil_test1, 0, 1000);
  tcase_add_loop_test(tc1_1, ceil_test2, 0, 1000);
  // 90
  tcase_add_test(tc1_1, p90);
  //
  tcase_add_loop_test(tc1_1, exp_test, S21_M_PI, S21_M_PI + 1000);
  tcase_add_loop_test(tc1_1, exp_test2, 0, 1000);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
